spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.228.128:3306/gulimail-sms
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.228.128:8848
        ip: localhost
  application:
    name: gulimail-coupon


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 7003
